config/routes.rb
Rails.application.routes.draw do

  resources :payplans

  resources :homes, only: [:index] do
    get :manual, on: :collection
  end

  root to: "homes#index"

  resources :payments do
    collection do
      post :result
      post :success
      post :fail
    end
  end

  resources :integrations, shallow: true do
    collection do
      get :install
      get :login
    end
    resources :review_integrations, shallow: true do
      resources :invoices, shallow: true, default: {invoiceable: "review_integrations"} do
        get :print, on: :member
      end
      get :get_reviews, on: :collection
    end
  end

  resources :accounts, only: [:show]

  constraints SubdomainConstraint do

    get '/dashboard/index' , to: 'dashboard#index'
    get '/dashboard/users', to: 'dashboard#users'
    get '/dashboard/test_email', to: 'dashboard#test_email'
    delete '/dashboard/user_destroy', to: 'dashboard#user_destroy'

  end

  devise_for :users, controllers: {
    sessions:       'users/sessions'
  }

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  authorize_resource :class => false

  def index
    # insint = current_user.insints.first
    # if insint.present?
    #   if insint.inskey.present?
    #     uri = "http://"+"#{insint.inskey}"+":"+"#{insint.password}"+"@"+"#{insint.subdomen}"+"/admin/products/count.json"
    #   else
    #     uri = "http://k-comment:"+"#{insint.password}"+"@"+"#{insint.subdomen}"+"/admin/products/count.json"
    #     url = "http://k-comment:"+"#{insint.password}"+"@"+"#{insint.subdomen}"+"/admin/account.json"
    #   end
    #     puts uri
    #     response = RestClient.get(uri)
    #     data = JSON.parse(response)
    #     @product_count = data['count']
    # end
    # clients = Client.all
    # izb_product_string = clients.map(&:izb_productid).join(',')
    # @count_izb = izb_product_string.split(',').count

  end # index

  def users
    # @q = User.ransack(params[:q])
    # @q.sorts = 'id desc' if @q.sorts.empty?
    # @users = @q.result.paginate(page: params[:page], per_page: 30)
  end

  def user_destroy
    # @user = User.find(params[:user_id])
    # @user.destroy
    # respond_to do |format|
    #   format.html { redirect_to dashboard_users_url, notice: 'User was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
  end

  def test_email
    # User.service_end_email
    # flash[:notice] = 'Отправили'
		# redirect_to dashboard_index_path
  end

end # index

app/views/dashboard/index.html.erb
<div class="row">
  <div class="col-12">
    <div class="clearfix">
      <h1 class="float-left">Главная</h1>
    </div>
    <p>
      Добро пожаловать <strong><% if current_user.admin? %> администратор - <%else%><%end%></strong><%=current_user.name %>!
    </p>
    <p>
      В вашем магазине товаров <%= @product_count %> шт
    </p>
    <p>
      В избранное добавлено товаров в кол-ве <%= @count_izb %> шт
    </p>

    <% if current_user.admin? %>
    <p><%= link_to "Test email", dashboard_test_email_path %></p>
    <%else%><%end%>
    
  </div>


</div>

app/views/dashboard/users.html.erb
<div class="row">
  <div class="col-3">
    <h1>Пользователи</h1>
    <p>Всего - <%= User.all.count%></p>
  </div>
  <%= search_form_for @q, url: url_for(controller: 'dashboard', action: 'users'), html: {class: 'form-inline col-9'}  do |f|%>
    <div class="form-group">
      <%= f.search_field :name_or_subdomain_or_email_cont_all, placeholder: 'Имя, домен, email', class: "form-control input-sm"%>
      <%= f.search_field :created_at_datebegin, placeholder: 'создан от', class: "form-control input-sm", autocomplete: "off" %>
      <%= f.search_field :valid_until_dateend, placeholder: 'valid до', class: "form-control input-sm", autocomplete: "off"%>
      <%= f.submit 'Поиск', class: 'btn btn-info' %>
      <%= link_to 'Сбросить',dashboard_users_path, class: 'btn btn-link' %>
    </div>
  <% end %>
</div>

<div class="table-responsive">
<table class="table table-hover table-condensed table-sm">
  <thead class="thead-light">
    <tr>
      <th>Имя</th>
      <th>Логин</th>
      <th>Email</th>
      <th>Создан</th>
      <th>Обновлён</th>
      <th>Последний вход</th>
      <th>Действует до</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.subdomain %></td>
        <td><%= user.email %></td>
        <td><%= user.created_at %></td>
        <td><%= user.updated_at %></td>
        <td><%= user.last_sign_in_at %></td>
        <td><%= user.valid_until %></td>
        <td><%= link_to '<i class="fa fa-trash" aria-hidden="true"></i>'.html_safe, dashboard_user_destroy_path(:user_id => user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>
<div class="digg_pagination">
	<%= will_paginate @users %>
</div>