config/routes.rb
Rails.application.routes.draw do

  resources :payplans

  resources :homes, only: [:index] do
    get :manual, on: :collection
  end

  root to: "homes#index"

  resources :payments do
    collection do
      post :result
      post :success
      post :fail
    end
  end

  resources :integrations, shallow: true do
    collection do
      get :install
      get :login
    end
    resources :review_integrations, shallow: true do
      resources :invoices, shallow: true, default: {invoiceable: "review_integrations"} do
        get :print, on: :member
      end
      get :get_reviews, on: :collection
    end
  end

  resources :accounts, only: [:show]

  constraints SubdomainConstraint do

    get '/dashboard/index' , to: 'dashboard#index'
    get '/dashboard/users', to: 'dashboard#users'
    get '/dashboard/test_email', to: 'dashboard#test_email'
    delete '/dashboard/user_destroy', to: 'dashboard#user_destroy'

  end

  devise_for :users, controllers: {
    sessions:       'users/sessions'
  }

end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :user
  belongs_to :payplan
  belongs_to :invoiceable, polymorphic: true
  has_one :payment, dependent: :destroy

  after_update :change_invoiceable

  private

  def change_invoiceable
    invoiceable.update(status: true) if status == 'Оплачен'
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_invoiceable, only: [:new, :create]
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  authorize_resource

  def index
    @invoices = Invoice.all
  end

  def show; end

  def new
    @invoice = Invoice.new
  end

  def create
    @invoice = @invoiceable.build_invoice(invoice_params)
    payplan = Payplan.find(invoice_params[:payplan_id])
    @invoice.sum = payplan.price
    @invoice.user = current_user
    if @invoice.save
      @payment = @invoice.build_payment(
        paymenttype: @invoice.paymenttype
      )
      @payment.user = current_user
      @payment.payplan = @invoice.payplan
      @payment.subdomain = current_user.subdomain
      @payment.save
      redirect_to @invoice
    else
      render :new
    end
  end

  def edit; end

  def update
    if @invoice.update(invoice_params)
      redirect_to @invoice
    else
      render :edit
    end
  end

  def destroy
    @invoice.destroy
    redirect_to current_user.account
  end
  # TODO настроить печать инвойса
  def print
    # @company = Company.first
    # @invoice = Invoice.find(params[:invoice_id])
    # respond_to do |format|
    #   format.html
    #   format.pdf do
    #     render :pdf => "Счёт #{@invoice.id}",
    #            :template => "invoices/pdfsight",
    #            :show_as_html => params.key?('debug')
    #   end
    # end
  end

  private

  def set_invoiceable
    @invoiceable = name.classify.constantize.find(params["#{name.singularize}_id".to_sym])
  end

  def name
    params[:default][:invoiceable]
  end

  def set_invoice
    @invoice = Invoice.find(params[:id])
  end

  def invoice_params
    params.require(:invoice).permit(:payertype, :paymenttype, :payplan_id, :status, :sum)
  end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.slim
= form_with model: [@invoiceable, @invoice], local: true do |f|
  .payplan-wrapper.mt-3
    p.mt-2.mb-1
      | Выберите тип плательщика:
      .d-flex
        = f.collection_radio_buttons :payertype, [['fiz', 'Физ лицо'], ['ur', 'Юр лицо']], :first, :last, checked: 'fiz' do |b|
          .paymenttype.p-2
            span.ms-2 = b.radio_button
            span.mx-2 = b.label
  .payplan-wrapper.mt-3
    p.mt-2.mb-1
      | Выберите способ оплаты:
      .d-flex
        = f.collection_radio_buttons :paymenttype, [['invoice', 'Счёт для юр лиц'],['creditcard', 'Кредитные карты'], ['paypal', 'Paypal']], :first, :last, checked: 'creditcard' do |b|
          .paymenttype.p-2

            span.ms-2 = b.radio_button
            - if b.text == "Кредитные карты"
              span.mx-2
                = image_tag 'visa_master.svg', data: {src: 'visa_master.svg'}, class: 'visa-master'
                | <br>
                | Webmoney, Сбербанк Онлайн, Apple Pay, Яндекс.Деньги, Альфа-Клик
            - else
              span.mx-2 = b.label
  .payplan-wrapper.mt-3
    p.mt-2.mb-1
      | Тарифные планы:
      .d-flex
        = f.collection_radio_buttons :payplan_id, Payplan.where(for: "ReviewIntegration"), :id, :period_price, checked: Payplan.where(for: "ReviewIntegration").max_by{|p| p[:price] }.id  do |b|
          .paymenttype.p-2
            span.ms-2 = b.radio_button
            span.mx-2 = b.label

  .mt-4
    = f.submit

app/views/invoices/create.html.slim
h1 Invoices#create
p Find me in app/views/invoices/create.html.slim

app/views/invoices/destroy.html.slim
h1 Invoices#destroy
p Find me in app/views/invoices/destroy.html.slim

app/views/invoices/edit.html.slim
.d-flex.justify-content-center.mt-5
  .content
    h1 Редактировать Счет
    = form_with model: @invoice, local: true do |f|
      .payplan-wrapper.mt-3
        p.mt-2.mb-1
          | Выберите тип плательщика:
          .d-flex
            = f.collection_radio_buttons :payertype, [['fiz', 'Физ лицо'], ['ur', 'Юр лицо']], :first, :last, checked: 'fiz' do |b|
              .paymenttype.p-2
                span.ms-2 = b.radio_button
                span.mx-2 = b.label
      .payplan-wrapper.mt-3
        p.mt-2.mb-1
          | Выберите способ оплаты:
          .d-flex
            = f.collection_radio_buttons :paymenttype, [['invoice', 'Счёт для юр лиц'],['creditcard', 'Кредитные карты'], ['paypal', 'Paypal']], :first, :last, checked: 'creditcard' do |b|
              .paymenttype.p-2

                span.ms-2 = b.radio_button
                - if b.text == "Кредитные карты"
                  span.mx-2
                    = image_tag 'visa_master.svg', data: {src: 'visa_master.svg'}, class: 'visa-master'
                    | <br>
                    | Webmoney, Сбербанк Онлайн, Apple Pay, Яндекс.Деньги, Альфа-Клик
                - else
                  span.mx-2 = b.label
      .payplan-wrapper.mt-3
        p.mt-2.mb-1
          | Тарифные планы:
          .d-flex
            = f.collection_radio_buttons :payplan_id, Payplan.where(for: "ReviewIntegration"), :id, :period_price, checked: Payplan.where(for: "ReviewIntegration").max_by{|p| p[:price] }.id  do |b|
              .paymenttype.p-2
                span.ms-2 = b.radio_button
                span.mx-2 = b.label

      .mt-4
        = f.submit class: "btn btn-primary mt-4"

      = link_to "Invoice", @invoice, class: "btn btn-outline-primary mt-4"

app/views/invoices/index.html.slim
h1 Invoices#index
p Find me in app/views/invoices/index.html.slim

app/views/invoices/new.html.slim
.d-flex.justify-content-center.mt-5
  .content
    h1 Новый Счет
    = render 'form', invoice: @invoice

app/views/invoices/print.html.slim
h1 Invoices#print
p Find me in app/views/invoices/print.html.slim

app/views/invoices/show.html.slim
.d-flex.justify-content-center.mt-5
  .content
    h2.mb-3 Cчёт № #{@invoice.id} на оплату сервиса
    p
      strong Период продления: #{@invoice.payplan.period}

    p
      strong Сумма счета: #{@invoice.sum}

    p
      strong Статус счета: #{@invoice.status}

    strong Cпособ оплаты:
    .card-columns
      - if @invoice.paymenttype == 'invoice'
        .card.bg-light.text-center#invoice
          img.card-img-top(src="/pdf.png" alt="Card image" style="width:12%")
          .card-body.text-center
            p.card-text Счёт для юр лиц (pdf)
            = link_to "Распечатать счет", invoice_print_path(@invoice, :format => :pdf), {class: 'btn btn-primary stretched-link', target: '_blank'}

      - if @invoice.paymenttype == 'paypal'
        .card.bg-light.text-center#paypal
          img.card-img-top(src="/paypal.png" alt="Card image" style="width:50%;")
          .card-body.text-center
            - if @invoice.status == "Не оплачен"
              a.btn.btn-primary.stretched-link(href="#") Перейти к оплате

      - if @invoice.paymenttype == 'creditcard'
        .card.bg-light.text-center#creditcard
          = image_tag 'visa_master.svg', data: {src: 'visa_master.svg'}, class: 'visa-master card-img-top'
          / img.card-img-top(src="/visa-master.png" alt="Card image" style="width:56%;")
          .card-body.text-center
            - if @invoice.status == "Не оплачен"
              a (href="https://paymaster.ru/ru-RU/Payment/Init?LMI_MERCHANT_ID=e4e9a4a9-8ce0-494d-a09a-66e324e32968&LMI_CURRENCY=RUB&LMI_PAYMENT_AMOUNT=#{@invoice.sum}&LMI_PAYMENT_DESC=#{@invoice.payplan.period}&LMI_PAYMENT_NO=#{@invoice.id}&CURRENT_USER=#{current_user.id}&LMI_OPEN_INVOICE=0&LMI_SIM_MODE=0" class="btn btn-primary stretched-link") Перейти к оплате
              / a (href="https://paymaster.ru/ru-RU/Payment/Init?LMI_MERCHANT_ID=52d455b2-cf83-49eb-9096-d5590cac2a7c&LMI_CURRENCY=RUB&LMI_PAYMENT_AMOUNT=#{@invoice.sum}&LMI_PAYMENT_DESC=#{@invoice.payplan.period}&LMI_PAYMENT_NO=#{@invoice.id}&CURRENT_USER=#{current_user.id}&LMI_OPEN_INVOICE=0&LMI_SIM_MODE=0" class="btn btn-primary stretched-link") Перейти к оплате

      .btn-group.mt-5
        - if @invoice.status != 'Оплачен'
          = link_to 'Редактировать', edit_invoice_path(@invoice) , class: 'btn btn-primary'
          = link_to 'Удалить счет', @invoice, method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-danger'
        = link_to 'Account', current_user.account , class: 'btn btn-outline-primary'

app/views/invoices/update.html.slim
h1 Invoices#update
p Find me in app/views/invoices/update.html.slim