config/routes.rb
Rails.application.routes.draw do

  resources :payplans

  resources :homes, only: [:index] do
    get :manual, on: :collection
  end

  root to: "homes#index"

  resources :payments do
    collection do
      post :result
      post :success
      post :fail
    end
  end

  resources :integrations, shallow: true do
    collection do
      get :install
      get :login
    end
    resources :review_integrations, shallow: true do
      resources :invoices, shallow: true, default: {invoiceable: "review_integrations"} do
        get :print, on: :member
      end
      get :get_reviews, on: :collection
    end
  end

  resources :accounts, only: [:show]

  constraints SubdomainConstraint do

    get '/dashboard/index' , to: 'dashboard#index'
    get '/dashboard/users', to: 'dashboard#users'
    get '/dashboard/test_email', to: 'dashboard#test_email'
    delete '/dashboard/user_destroy', to: 'dashboard#user_destroy'

  end

  devise_for :users, controllers: {
    sessions:       'users/sessions'
  }

end

app/models/payplan.rb
class Payplan < ApplicationRecord
  has_many :invoices
  validates :period, :price, presence: true

  def period_price
    "Тариф на <strong>#{period}</strong> за #{price} руб.".html_safe
  end

end

app/controllers/payplans_controller.rb
class PayplansController < ApplicationController
  before_action :authenticate_user!
  before_action :set_payplan, only: [:show, :edit, :update, :destroy]

  authorize_resource

  def index
    @payplans = Payplan.all
  end

  def show; end

  def new
    @payplan = Payplan.new
  end

  def create
    @payplan = Payplan.new(payplan_params)

    if @payplan.save
      redirect_to payplans_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @payplan.update(payplan_params)
      redirect_to @payplan
    else
      render :edit
    end
  end

  def destroy
    @payplan.destroy
    redirect_to payplans_path
  end

  private

  def set_payplan
    @payplan = Payplan.find(params[:id])
  end

  def payplan_params
    params.require(:payplan).permit(:period, :price, :for)
  end
end

app/helpers/payplans_helper.rb
module PayplansHelper
end

app/views/payplans/_form.html.slim
= form_with model: @payplan, local: true do |f|

  .payplan-wrapper.mt-3
    p.mt-2.mb-1
      = f.label :period, class: "form-label"
      = f.text_field :period, class: "form-control"
  .payplan-wrapper.mt-3
    p.mt-2.mb-1
      = f.label :price, class: "form-label"
      = f.text_field :price, class: "form-control"
  .payplan-wrapper.mt-3
    p.mt-2.mb-1
      = f.label :for, class: "form-label"
      = f.text_field :for, class: "form-control"

  .payplan-wrapper.mt-3
    p.mt-2.mb-1
    = f.submit class: 'btn btn-primary my-3'
    | <br>
    = link_to 'Назад', payplans_path, class: 'btn btn-outline-primary'

app/views/payplans/_payplan.html.slim
tr
  td = payplan.period
  td = payplan.price
  td = payplan.for

  - if can? :read, payplan
    td = link_to 'Show', payplan
  - if can? :edit, payplan
    td = link_to 'Edit', edit_payplan_path(payplan)
    td = link_to 'Destroy', payplan, method: :delete, data: { confirm: 'Are you sure?' }

app/views/payplans/create.html.slim
h1 Payplans#create
p Find me in app/views/payplans/create.html.slim

app/views/payplans/destroy.html.slim
h1 Payplans#destroy
p Find me in app/views/payplans/destroy.html.slim

app/views/payplans/edit.html.slim
h1 Payplan Edit
= render "form"

app/views/payplans/index.html.slim
h1 Payplans

table
  thead
    tr
      th Period
      th Price
      th For
      th colspan="3"

  tbody
    = render @payplans

br
- if can? :edit, Payplan
  = link_to 'New Payplan', new_payplan_path

app/views/payplans/new.html.slim
.d-flex.justify-content-center.mt-5
  .content
    h1 Payplan New
    = render "form"

app/views/payplans/show.html.slim
h1 Payplan

p
  | Period:
  =< @payplan.period
p
  | Price:
  =< @payplan.price

= link_to "Назад", payplans_path

app/views/payplans/update.html.slim
h1 Payplans#update
p Find me in app/views/payplans/update.html.slim