config/routes.rb
Rails.application.routes.draw do

  resources :payplans

  resources :homes, only: [:index] do
    get :manual, on: :collection
  end

  root to: "homes#index"

  resources :payments do
    collection do
      post :result
      post :success
      post :fail
    end
  end

  resources :integrations, shallow: true do
    collection do
      get :install
      get :login
    end
    resources :review_integrations, shallow: true do
      resources :invoices, shallow: true, default: {invoiceable: "review_integrations"} do
        get :print, on: :member
      end
      get :get_reviews, on: :collection
    end
  end

  resources :accounts, only: [:show]

  constraints SubdomainConstraint do

    get '/dashboard/index' , to: 'dashboard#index'
    get '/dashboard/users', to: 'dashboard#users'
    get '/dashboard/test_email', to: 'dashboard#test_email'
    delete '/dashboard/user_destroy', to: 'dashboard#user_destroy'

  end

  devise_for :users, controllers: {
    sessions:       'users/sessions'
  }

end

app/models/review_integration.rb
class ReviewIntegration < ApplicationRecord
  belongs_to :user
  belongs_to :integration
  has_one :invoice, as: :invoiceable

  after_create :init_review_integration
  after_destroy :delete_review_integration

  private

  def init_review_integration
    Services::Review::SetupInsales.new(self).call
    update(ready: true)
  end

  def delete_review_integration
    Services::Review::DeleteInsales.new(self).call
  end
end

app/controllers/review_integrations_controller.rb
class ReviewIntegrationsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :destroy]
  before_action :set_integration, only: [:new, :create, :get_reviews]
  before_action :set_review_integration, only: [:destroy]

  authorize_resource

  def new
    @review_integration = ReviewIntegration.new
  end

  def create
    @review_integration = @integration.build_review_integration({
                                                                insalesid: current_user.integration.insalesid,
                                                                subdomain: @integration.subdomain
                                                            })
    @review_integration.user = current_user
    if @review_integration.save
      redirect_to current_user.account
    else
      render :new
    end
  end

  def destroy
    @review_integration.destroy
    redirect_to current_user.account
  end

  def get_reviews
    @review_integration = ReviewIntegration.find_by_subdomain(params[:host])

    if @review_integration.status
      @integration = @review_integration.integration
      @url_domain = Services::Insales::UrlDomain.new(@integration).call

      @reviews_with_image = get_reviews_wtih_image
      render json: { reviews: @reviews_with_image, success: true }
    end
  end

  private

  def get_reviews_wtih_image
    reviews = api_get_reviews
    reviews.map do |review|
      product = api_get_products(review["product_id"])
      review['product_title'] = product['title']
      review['product_permalink'] = product['permalink']
      review['product_image'] = product['images'].first['thumb_url'] if product['images'].present?
      review
    end
  end

  def api_get_reviews
    uri = "#{@url_domain}/admin/reviews.json"

    RestClient.get( uri, :accept => :json, :content_type => "application/json") do |response, request, result, &block|
      case response.code
      when 200
        JSON.parse response.body
      when 422
        puts "error 422"
        puts response
      when 404
        puts 'error 404'
        puts response
      when 503
        sleep 1
        puts 'sleep 1 error 503'
      else
        response.return!(&block)
      end
    end
  end

  def api_get_products(id)
    uri = "#{@url_domain}/admin/products/#{id}.json"

    RestClient.get( uri, :accept => :json, :content_type => "application/json") do |response, request, result, &block|
      case response.code
      when 200
        JSON.parse response.body
      when 422
        puts "error 422"
        puts response
      when 404
        puts 'error 404'
        puts response
      when 503
        sleep 1
        puts 'sleep 1 error 503'
      else
        response.return!(&block)
      end
    end
  end

  def set_review_integration
    @review_integration = ReviewIntegration.find(params[:id])
  end
  def set_integration
    @integration = Integration.find(params[:integration_id])
  end
end

app/helpers/review_integrations_helper.rb
module ReviewIntegrationsHelper
end

app/views/review_integrations/_review_integration.html.slim
- resource = current_user.integration.review_integration
- integration = current_user.integration
.header__review_integration.d-flex.mb-2
  h4.service__head Reviews
  span
    - if resource
      - if resource.ready
        span.info-integration Установлена
      - else
        span.warning-integration Не установлена

      - if resource.status
        span.info-integration Оплачена
      - else
        span.warning-integration Не оплачена
    - else
      span.warning-integration Не установлена
      span.warning-integration Не оплачена

- if resource
  - if resource.status
    = link_to "Счет <i class='fa fa-check' style='color:white'></i>".html_safe, resource.invoice, class: "btn btn-success me-2"
    = link_to "Удалить интеграцию", review_integration_path(resource), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger me-2"
  - else
    - if resource.invoice
      = link_to "Счет", resource.invoice, class: "btn btn-info me-2"
    - else
      = link_to "Создать счет", new_review_integration_invoice_path(resource), class: "btn btn-info me-2"
    = link_to "Удалить интеграцию", review_integration_path(resource), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger me-2"
- else
  = link_to "Создать интеграцию", new_integration_review_integration_path(integration), class: "btn btn-primary me-2"

app/views/review_integrations/new.html.slim
.d-flex.justify-content-center
  .content
    h1 ReviewIntegrations New
    = form_with model: [@integration, @review_integration], local: true do |f|
      p У этого типа сервиса нет атрибутов для заполнения.
      = f.submit